//Script GUID:2fcc26a3-4216-4cb9-acb0-074f8272c505
//Used for tracking history

#DECLARE Input_Redball_Path string = @"C:\Users\jianlez\Desktop\data\ballsCombination.log";
#DECLARE Extract_Redball_View string = @"Schema_RedBall.view";
#DECLARE Output_1ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\1Ball.log";
#DECLARE Output_2ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\2Ball.log";
#DECLARE Output_3ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\3Ball.log";
#DECLARE Output_4ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\4Ball.log";
#DECLARE Output_5ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\5Ball.log";
#DECLARE Output_6ball_Path string = @"C:\Users\jianlez\Desktop\data\0P\6Ball.log";


redBallData = 
    VIEW @Extract_Redball_View 
    PARAMS
    (
        streamPath = @Input_Redball_Path
    );

OneBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 1;

OneBallData = 
    SELECT RedBalls,
    COUNT() AS OneBallCount
    FROM OneBallData
    GROUP BY RedBalls
    ORDER BY OneBallCount DESC;

TwoBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 2;

TwoBallData = 
    SELECT RedBalls,
    COUNT() AS TwoBallCount
    FROM TwoBallData
    GROUP BY RedBalls
    ORDER BY TwoBallCount DESC;

ThreeBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 3;

ThreeBallData = 
    SELECT RedBalls,
           COUNT() AS ThreeBallCount
    FROM ThreeBallData
    GROUP BY RedBalls
    ORDER BY ThreeBallCount DESC;

FourBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 4;

FourBallData = 
    SELECT RedBalls,
           COUNT() AS FourBallCount
    FROM FourBallData
    GROUP BY RedBalls
    ORDER BY FourBallCount DESC;

FiveBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 5;

FiveBallData = 
    SELECT RedBalls,
           COUNT() AS FiveBallCount
    FROM FiveBallData
    GROUP BY RedBalls
    ORDER BY FiveBallCount DESC;

SixBallData = 
    SELECT RedBalls 
    FROM redBallData
    WHERE RedBalls.Length == 6;

SixBallData = 
    SELECT RedBalls,
           COUNT() AS SixBallCount
    FROM SixBallData
    GROUP BY RedBalls
    ORDER BY SixBallCount DESC;


OUTPUT OneBallData 
TO @Output_1ball_Path;

OUTPUT TwoBallData 
TO @Output_2ball_Path;

OUTPUT ThreeBallData 
TO @Output_3ball_Path;

OUTPUT FourBallData 
TO @Output_4ball_Path;

OUTPUT FiveBallData 
TO @Output_5ball_Path;

OUTPUT SixBallData 
TO @Output_6ball_Path;